services:
  equity_calculator:
    container_name: equity_calculator
    build:
      context: .
    volumes:
      - .:/usr/app/src
    working_dir: /usr/app/src
    command: python scripts/calculate.py
  db_equity_calculator:
    container_name: db_equity_calculator
    image: postgres:latest
    restart: always
    ports:
      - "5466:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: equity_calculator