CREATE TABLE IF NOT EXISTS Equity (
    id SERIAL PRIMARY KEY,
    First VARCHAR(100),
    Second VARCHAR(100),
    A VARCHAR(100),
    B VARCHAR(100),
    C VARCHAR(100),
    D VARCHAR(100),
    E VARCHAR(100),
    F VARCHAR(100),
    Concat VARCHAR(100),
    Equity VARCHAR(100),
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);